use crate::kind_src::KindsSrc;

pub const TURTLE_KINDS_SRC: KindsSrc = KindsSrc {
    punct: &[
        (".", "DOT"),
        (";", "SEMICOLON"),
        (",", "COMMA"),
        ("[", "L_BRACK"),
        ("]", "R_BRACK"),
        ("(", "L_PAREN"),
        (")", "R_PAREN"),
        ("^^", "CARET_CARET"),
    ],
    keywords: &[
        "prefix",
        "base",
        "a",
        "true",
        "false",
        "SPARQL_BASE",
        "SPARQL_PREFIX",
    ],
    literals: &[
        "TURTLE_IRIREF_LITERAL",
        "TURTLE_PNAME_NS_LITERAL",
        "TURTLE_PNAME_LN_LITERAL",
        "TURTLE_BLANK_NODE_LABEL_LITERAL",
        "TURTLE_LANGTAG_LITERAL",
        "TURTLE_INTEGER_LITERAL",
        "TURTLE_DECIMAL_LITERAL",
        "TURTLE_DOUBLE_LITERAL",
        "TURTLE_STRING_LITERAL_QUOTE",
        "TURTLE_STRING_LITERAL_SINGLE_QUOTE",
        "TURTLE_STRING_LITERAL_LONG_QUOTE",
        "TURTLE_STRING_LITERAL_LONG_SINGLE_QUOTE",
    ],
    tokens: &[
        "ERROR_TOKEN",
        "NEWLINE",
        "WHITESPACE",
        "COMMENT",
        "TURTLE_ANON_TOKEN",
    ],
    nodes: &[
        "TURTLE_ROOT",
        "TURTLE_STATEMENT_LIST",
        "TURTLE_PREFIX_DECLARATION",
        "TURTLE_BASE_DECLARATION",
        "TURTLE_SPARQL_PREFIX_DECLARATION",
        "TURTLE_SPARQL_BASE_DECLARATION",
        "TURTLE_TRIPLES",
        "TURTLE_PREDICATE_OBJECT_LIST",
        "TURTLE_PREDICATE_OBJECT_PAIR",
        "TURTLE_PREDICATE_OBJECT_PAIR_LIST",
        "TURTLE_OBJECT_LIST",
        "TURTLE_SUBJECT",
        "TURTLE_VERB",
        "TURTLE_OBJECT",
        "TURTLE_IRI",
        "TURTLE_PREFIXED_NAME",
        "TURTLE_BLANK_NODE",
        "TURTLE_BLANK_NODE_PROPERTY_LIST",
        "TURTLE_COLLECTION",
        "TURTLE_COLLECTION_OBJECT_LIST",
        "TURTLE_RDF_LITERAL",
        "TURTLE_NUMERIC_LITERAL",
        "TURTLE_BOOLEAN_LITERAL",
        "TURTLE_DATATYPE_ANNOTATION",
        "TURTLE_STRING",
        // Bogus nodes for error recovery
        "TURTLE_BOGUS",
        "TURTLE_BOGUS_STATEMENT",
    ],
};
