//! Generated file, do not edit by hand, see `xtask/codegen`

//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Group description generated by proc macro at compile time."]
#![doc = r""]
#![doc = r" To add a new rule, create a `.rs` file in the group subdirectory"]
#![doc = r#" and "touches" the corresponding group files to trigger recompilation."#]
use biome_analyze_macros::declare_group_from_fs;
declare_group_from_fs! { category : "lint" , group : "nursery" }
